apiVersion: v2
name: memegag-services
description: "MemeGag microservices Helm chart"
type: application
version: 0.1.0
appVersion: "0.1.0"
maintainers:
  - name: Chaitanya Joshi
    email: chaitanyajoshi15@gmail.com
